version: "3"
services:
  db:
    image: "postgres"
    container_name: "area-pg-dev"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "pg-dev"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
